### ISSUE TITLE
about pretrained model

### ISSUE THREAD

**Issue by sillytheif** [Huangxt57/MINI-Net#2]
Hi,can you provide the pretrained model of C3D network and the audio feature extracted model? I wanna to conduct the experiments on other video datasets

**Comment by xuantengh** [comment]
Thanks for focusing. For C3D pre-traindd model, please refer to [this repo](https://github.com/kenshohara/video-classification-3d-cnn-pytorch). And for audio feature extracted model, we use VGGish [here](https://github.com/harritaylor/torchvggish).
